<a href="https://colab.research.google.com/github/ronnymunthe99/PythonForDataScience/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY-PANDAS

Ronny Dominikus Munthe

# Transfer Data From Numpy To Pandas

Seperti Numpy dan Matplotlib, Pandas merupakan sebuah library python untuk data science, Pandas(Python For Data Analytics) juga memiliki struktur data yang kuat dan sangat mudah digunakan, serta fungsi-fungsi didalamnya yang cepat dalam melakukan operasi pada struktur tertentu. Pada pandas ini akan banyak ditemukan yang namanya dataframe

## Create data

Pada contoh ini, akan digunakan beruang sebagai objeknya

Kita dapat mengkategorikan seekor beruang dari ukurannya. Atau lebih tepatnya, dari ukuran-ukurannya: misalnya, ukuran kakinya, panjang rata-rata bulunya, ukuran ekornya, dan diameter perutnya.

In [1]:
import numpy as np
a_bear_numpy = np.array([100,5,20,80])
a_bear_numpy

array([100,   5,  20,  80])

In [4]:
bear_family = [    
    [100, 5  , 20, 80], 
    # Bear mom
    [50 , 2.5, 10, 40], 
    # Bear baby
    [110, 6  , 22, 80], 
    # Bear dad
    ]

bear_family_numpy = np.array(bear_family)
bear_family_numpy

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.5,  10. ,  40. ],
       [110. ,   6. ,  22. ,  80. ]])

In [5]:
# cara menunjukkan lokasi angka dengan representasi (Baris, Kolom) yang pengideksannya dimulai dari 0
bear_family_numpy[2, 0] 

110.0

In [6]:
bear_family_numpy[:, 0]

array([100.,  50., 110.])

# Get To Know Pandas

Semuanya dalam bentuk tabel dengan representasi baris dan kolom

In [7]:
bear_family = [    
    [100, 5  , 20, 80],    
    [50 , 2.5, 10, 40],    
    [110, 6  , 22, 80],]

Membuat sebuah dataframe dari tabel yang sudah dibuat diatas

In [8]:
import pandas as pd
bear_family_df = pd.DataFrame(bear_family)
bear_family_df

0    1   2   3
0  100  5.0  20  80
1   50  2.5  10  40
2  110  6.0  22  80

Karena library Pandas banyak didasarkan pada Numpy, maka kita bisa mengirimkan data berformat ndarray ke dataframe

In [10]:
# Memberi label pada index dan 
bear_family_df = pd.DataFrame(bear_family_numpy, 
                index = ['mom', 'baby', 'dad'],
                columns = ['leg', 'hair', 'tail', 'belly']
            )

bear_family_df

leg  hair  tail  belly
mom   100.0   5.0  20.0   80.0
baby   50.0   2.5  10.0   40.0
dad   110.0   6.0  22.0   80.0

Objek dataframe ini cukup mirip dengan konsep kerangka format lain seperti, MySQL, PostgreSQL yang dimanipulasi dengan SQL, Excel, JSON, XML, dan lain-lain. Oleh karena itu, dengan Pandas kita juga bisa membaca data-data berformat tersebut 

# Digging Into DataFrames

Kali ini, akan kita lihat slicing dan indexing pada dataframe

In [11]:
bear_family_df.belly
bear_family_df["belly"]

mom     80.0
baby    40.0
dad     80.0
Name: belly, dtype: float64

bear_family_df.belly akan menghasilkan data objek bertipe pandas.series yang artinya hanya terdapat 1 kolom. Dan, bear_family_df["belly"] akan menghasilkan values atau nilai pada kolom tersebut


Kita juga bisa dapat melihat data satu per satu, berkat metode iterrows, yang akan mengembalikan (pada setiap iterasi loop for) tuple yang elemen pertamanya adalah indeks baris, dan elemen kedua adalah value dari baris tersebut

## Iterrows looping-for

In [12]:
for ind_row, content_row in bear_family_df.iterrows():
    print("Here is %s bear:" % ind_row)
    print(content_row)
    print("--------------------")

Here is mom bear:
leg      100.0
hair       5.0
tail      20.0
belly     80.0
Name: mom, dtype: float64
--------------------
Here is baby bear:
leg      50.0
hair      2.5
tail     10.0
belly    40.0
Name: baby, dtype: float64
--------------------
Here is dad bear:
leg      110.0
hair       6.0
tail      22.0
belly     80.0
Name: dad, dtype: float64
--------------------


## Indexing and Slicing

In [15]:
bear_family_df.iloc[2] 
# iloc adalah indeks posisi


leg      110.0
hair       6.0
tail      22.0
belly     80.0
Name: dad, dtype: float64

In [14]:
bear_family_df.loc["dad"] 
# loc adalah indeks berbasis label

leg      110.0
hair       6.0
tail      22.0
belly     80.0
Name: dad, dtype: float64

## Filtering

In [16]:
bear_family_df["belly"] == 80

mom      True
baby    False
dad      True
Name: belly, dtype: bool

Mask dalam Pandas berfungsi mempertahankan beberapa baris DataFrame dan menyembunyikan yang lain. Dalam Pandas, mask adalah daftar variabel Boolean (True atau False) di mana setiap elemen terkait dengan sebuah baris dari DataFrame. Jika elemen ini True, kita akan ingin mempertahankan baris yang bersangkutan. Jika kita tidak ingin mempertahankan baris tersebut, maka elemen ini adalah False.

In [19]:
mask = bear_family_df["belly"] == 80
bears_80 = bear_family_df[mask]
bears_80

leg  hair  tail  belly
mom  100.0   5.0  20.0   80.0
dad  110.0   6.0  22.0   80.0

In [21]:
mask

mom      True
baby    False
dad      True
Name: belly, dtype: bool

In [20]:
# Atau dengan cara lain
bears_80 = bear_family_df[bear_family_df["belly"] == 80]

bears_80

leg  hair  tail  belly
mom  100.0   5.0  20.0   80.0
dad  110.0   6.0  22.0   80.0

# Adding New Data To A Dataframe

In [23]:
# menambahkan some _bears ke dalam bear_family_df yang akan disimpan di variabel all_bears
some_bears = pd.DataFrame([[105,4,19,80],[100,5,20,80]],
# 2 bear baru
columns = bear_family_df.columns) 
all_bears = bear_family_df.append(some_bears)
all_bears

leg  hair  tail  belly
mom   100.0   5.0  20.0   80.0
baby   50.0   2.5  10.0   40.0
dad   110.0   6.0  22.0   80.0
0     105.0   4.0  19.0   80.0
1     100.0   5.0  20.0   80.0

In [24]:
# Menghapus data yang isinya sama (data duplikat)
all_bears.drop_duplicates()

leg  hair  tail  belly
mom   100.0   5.0  20.0   80.0
baby   50.0   2.5  10.0   40.0
dad   110.0   6.0  22.0   80.0
0     105.0   4.0  19.0   80.0

# Adding A new Columns to A Dataframe

In [26]:
# Mendapatkan nama kolom
bear_family_df.columns

Index(['leg', 'hair', 'tail', 'belly', 'sex'], dtype='object')

In [27]:
# Mendapatkan jnumlah baris
len(bear_family_df)

3

In [31]:
# Membuat nama kolom yang berisi string
bear_family_df["sex"] = ["f", "f", "m"]
bear_family_df

leg  hair  tail  belly sex
mom   100.0   5.0  20.0   80.0   f
baby   50.0   2.5  10.0   40.0   f
dad   110.0   6.0  22.0   80.0   m

In [32]:
# mendapatkan nilai unik dari kolom belly
bear_family_df.belly.unique()

array([80., 40.])

In [34]:
# Untuk membaca file yang tidak ada di direktori saat ini
import os
os.getcwd()

'/content'